server:
  port: 8080
spring:
  datasource:
    username: Manishka
    password: postgres

    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/client_db

  jpa:
    show-sql: true
    hibernate.ddl-auto: update
