server:
  port:
spring:
  datasource:
    username:
    password:

    driver-class-name:
    url:

  jpa:
    show-sql: false
    hibernate.ddl-auto: update

  mvc:
    hiddenmethod:
      filter:
        enabled: true
